### PR TITLE
db.createWriteStream()

### PR DESCRIPTION
**Pull request by e-e-e**
Hey @mafintosh and @noffle, this PR adds a simple interface for creating a writable stream. It simply pushes the data into the db's batch method. I have made it so that the it accepts both objects and arrays of objects. This adds a bit of complexity, but also adds flexibility so that we can write batches to the stream.

Let me know your thoughts.

### CODE REVIEW

**Comment by mafintosh** [comment]
:+1: from me, @noffle any thoughts?

**Comment by noffle** [comment]
Is the idea that at some point the call to `batch` will be subbed out with real streaming writes?

**Comment by mafintosh** [comment]
@noffle this is streaming writes, the bulk stream makes batches corresponding to highWaterMark

**Comment by noffle** [comment]
Oh cool, I didn't realize this.

**Pull request merged**
