### PR TITLE
return null instead of [] on notfound

### PR DESCRIPTION
**Pull request by mafintosh**
unsure if this is a good idea. thoughts @e-e-e, @noffle, @andrewosh ?

### CODE REVIEW

**Comment by noffle** [comment]
What's the motivation? Do you foresee a future case where `[]` could be returned and not mean "not found"? Interested in hearing more on your thought process around this.

**Comment by andrewosh** [comment]
Similar questions to @noffle, though I do like having one consistent return type for the function -- can do one fewer check in the callback. Along the same lines as @noffle, is there any scenario where a `null` return value could be useful/meaningful (i.e. a simple way to check if a value was deleted without doing a checkout or a diff)?

If we're considering API-breaking changes, and what about the levelup approach of returning a "Key not found" error in this situation? Erring on the side of levelup's approach, especially when the rest of the API is so similar, always has appeal.

**Comment by noffle** [comment]
+1 on preferring `[]` if possible: guaranteeing a return type for all cases would be easiest on downstream.

**Comment by mafintosh** [comment]
Motivation was @e-e-e mentioned that's how it used to work. I'm perfectly fine keeping it as is

**Comment by e-e-e** [comment]
Oh also - I am not opinionated about this. It was just a breaking change I noticed between v2 and v3.
Although that said, could a deleted node be returned as an array with length > 0? In which case a user of the db would need additional checks for if its a deleted node.

**Comment by mafintosh** [comment]
@e-e-e that'll only happen in case of a conflict (if two writers disagree on the state of a key)

**Comment by mafintosh** [comment]
Closing as we're all in agreement that the array is cool

**Pull request closed without merging**
