### PR TITLE
return key and node from watch

### PR DESCRIPTION
**Pull request by m-onz**
I thought it would be handy to return the key and value from the watch so that you can act upon it. 

Currently the change event does not indicate which value was changed.

### CODE REVIEW

**Comment by noffle** [comment]
Nice, @m-onz. I think the `watch` callback can be called *once* after many keys were updated. Could you add a test for doing a `watch` when a batch insert of relevant keys is performed?

**Comment by m-onz** [comment]
Yes indeed. I will send another PR tomorrow 👍

**Comment by m-onz** [comment]
@noffle I can't seem to find the batch code anywhere?

**Comment by noffle** [comment]
Yeah, `master` is in kind of a weird state. `2.1.1` is the latest, and is what I think you should PR against. @mafintosh is building a rewrite directly on master, and it's still a work-in-progress and doesn't have API/feature parity yet.

**Comment by m-onz** [comment]
No problem. I'm currently building some rest ish api's on top of hyperdb.
Im hoping to release a project once everything becomes more static.

Thanks for responding I will hold fire on issues/ suggestions etc until the
dust settles!

**Comment by mafintosh** [comment]
@m-onz sounds like a neat app! i'm re-adding batch today

**Comment by m-onz** [comment]
Yay! 😁  @mafintosh Thanks for doing that. I am working on a library that
exposes a CRUD http server based on declarative models. I am looking
forward to sharing it with you guys I'm the coming week.

I might call it hypercrud! Unless I think of a better name for it.

Incidentally what would be a cool naming convention for hyperdb related
libraries?

Prefixing hyper onto stuff is fun for now. 🤔

**Comment by mafintosh** [comment]
@m-onz https://github.com/mafintosh/hyperdb/commit/79903ca3c21c562cf40cf5ffc99ad6c200e52832

Please link it to me as soon you have something. I think a cool idea would be to have an awesome-hyperdb list and track cool userland stuff there :)

**Comment by m-onz** [comment]
I'm on it! I will create an awesome-hyperdb repo tommorow when I'm at my
computer. I would love to help and curate it.

**Comment by m-onz** [comment]
Here is the initial Awesome-hyperdb repo: [Awesome-hyperDB](https://github.com/m-onz/Awesome-hyperdb).

**Comment by m-onz** [comment]
Closing this and re-opening another PR (or not) after 3.0.0 is on NPM

**Pull request closed without merging**
